### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by ahahn94** [The-Microservice-Dungeon/gamelog#14]
Unit tests for our service have to be implemented.

## Details
Our API should be validated by unit tests.
The unit tests should test whether the received data (payload, header) for example calls corresponds with what is expected according to the API specification. This makes sure that major errors are not only detected during the integration tests.

Furthermore, the rest of the business logic must also be secured by unit tests.

### Notice:
Only test our own functions / API calls, not the underlying technologies (Spring, Kafka).

**Comment by ahahn94** [comment]
@tobi6112 Do you have any additions?

**Comment by tobi6112** [comment]
> @tobi6112 Do you have any additions?

Fine for me
